// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Brahma.FSharp.OpenCL.Printer")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp")>]
[<assembly: AssemblyVersionAttribute("2.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-08-05T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("2.0.1")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","b560b4d38e30cc06a46a85080a9c69b2ddd57082")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Brahma.FSharp.OpenCL.Printer"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp"
    let [<Literal>] AssemblyVersion = "2.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-08-05T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "2.0.1"
    let [<Literal>] AssemblyInformationalVersion = "2.0.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "b560b4d38e30cc06a46a85080a9c69b2ddd57082"
