// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Brahma.FSharp.OpenCL.Shared")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp")>]
[<assembly: AssemblyVersionAttribute("3.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2024-04-09T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("3.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.0.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","alpha1")>]
[<assembly: AssemblyMetadataAttribute("GitHash","4f6a4f8525c2a72218b70bfff07942674fac2f8a")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Brahma.FSharp.OpenCL.Shared"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp"
    let [<Literal>] AssemblyVersion = "3.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2024-04-09T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "3.0.0"
    let [<Literal>] AssemblyInformationalVersion = "3.0.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "alpha1"
    let [<Literal>] AssemblyMetadata_GitHash = "4f6a4f8525c2a72218b70bfff07942674fac2f8a"
