// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Brahma.FSharp.OpenCL.Shared")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp")>]
[<assembly: AssemblyVersionAttribute("2.0.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-01-04T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("2.0.3")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","0d64bea9a5517d76be008f89514f7e4b3762fb19")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Brahma.FSharp.OpenCL.Shared"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp"
    let [<Literal>] AssemblyVersion = "2.0.3"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-01-04T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "2.0.3"
    let [<Literal>] AssemblyInformationalVersion = "2.0.3"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "0d64bea9a5517d76be008f89514f7e4b3762fb19"
