namespace Brahma.FSharp

[<RequireQualifiedAccess>]
type Platform =
    | Intel
    | Amd
    | Nvidia
    | Any
    | Custom of pattern: string

[<RequireQualifiedAccess>]
type DeviceType =
    | CPU
    | GPU
    | Default

[<Measure>]
type Byte

type DeviceExtension =
    | CL_INTEL_ACCELERATOR
    | CL_INTEL_ADVANCED_MOTION_ESTIMATION
    | CL_INTEL_COMMAND_QUEUE_FAMILIES
    | CL_INTEL_DEVICE_ATTRIBUTE_QUERY
    | CL_INTEL_DEVICE_SIDE_AVC_MOTION_ESTIMATION
    | CL_INTEL_DRIVER_DIAGNOSTICS
    | CL_INTEL_MEDIA_BLOCK_IO
    | CL_INTEL_MEM_FORCE_HOST_MEMORY
    | CL_INTEL_MOTION_ESTIMATION
    | CL_INTEL_PACKED_YUV
    | CL_INTEL_PLANAR_YUV
    | CL_INTEL_REQUIRED_SUBGROUP_SIZE
    | CL_INTEL_SHARING_FORMAT_QUERY
    | CL_INTEL_SPIRV_DEVICE_SIDE_AVC_MOTION_ESTIMATION
    | CL_INTEL_SPIRV_MEDIA_BLOCK_IO
    | CL_INTEL_SPIRV_SUBGROUPS
    | CL_INTEL_SPLIT_WORK_GROUP_BARRIER
    | CL_INTEL_SUBGROUPS
    | CL_INTEL_SUBGROUPS_CHAR
    | CL_INTEL_SUBGROUPS_LONG
    | CL_INTEL_SUBGROUPS_SHORT
    | CL_INTEL_UNIFIED_SHARED_MEMORY
    | CL_INTEL_VA_API_MEDIA_SHARING
    | CL_KHR_3D_IMAGE_WRITES
    | CL_KHR_BYTE_ADDRESSABLE_STORE
    | CL_KHR_CREATE_COMMAND_QUEUE
    | CL_KHR_DEPTH_IMAGES
    | CL_KHR_DEVICE_UUID
    | CL_KHR_FP16
    | CL_KHR_FP64
    | CL_KHR_GLOBAL_INT32_BASE_ATOMICS
    | CL_KHR_GLOBAL_INT32_EXTENDED_ATOMICS
    | CL_KHR_GL_SHARING
    | CL_KHR_ICD
    | CL_KHR_IL_PROGRAM
    | CL_KHR_IMAGE2D_FROM_BUFFER
    | CL_KHR_INT64_BASE_ATOMICS
    | CL_KHR_INT64_EXTENDED_ATOMICS
    | CL_KHR_LOCAL_INT32_BASE_ATOMICS
    | CL_KHR_LOCAL_INT32_EXTENDED_ATOMICS
    | CL_KHR_MIPMAP_IMAGE
    | CL_KHR_MIPMAP_IMAGE_WRITES
    | CL_KHR_PCI_BUS_INFO
    | CL_KHR_PRIORITY_HINTS
    | CL_KHR_SPIR
    | CL_KHR_SPIRV_NO_INTEGER_WRAP_DECORATION
    | CL_KHR_SUBGROUP_BALLOT
    | CL_KHR_SUBGROUP_CLUSTERED_REDUCE
    | CL_KHR_SUBGROUP_EXTENDED_TYPES
    | CL_KHR_SUBGROUP_NON_UNIFORM_ARITHMETIC
    | CL_KHR_SUBGROUP_NON_UNIFORM_VOTE
    | CL_KHR_SUBGROUP_SHUFFLE
    | CL_KHR_SUBGROUP_SHUFFLE_RELATIVE
    | CL_KHR_SUBGROUPS
    | CL_KHR_SUGGESTED_LOCAL_WORK_SIZE
    | CL_KHR_THROTTLE_HINTS
    | CL_NV_COMPILER_OPTIONS
    | CL_NV_COPY_OPTS
    | CL_NV_CREATE_BUFFER
    | CL_NV_DEVICE_ATTRIBUTE_QUERY
    | CL_NV_PRAGMA_UNROLL
    | OTHER of string

type IDevice =
    abstract Name: string
    abstract Platform: Platform
    abstract DeviceType: DeviceType

    abstract MaxWorkGroupSize: int
    abstract MaxWorkItemDimensions: int
    abstract MaxWorkItemSizes: int[]

    abstract LocalMemSize: int<Byte>
    abstract GlobalMemSize: int64<Byte>

    abstract DeviceExtensions: array<DeviceExtension>
