// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Brahma.FSharp.Tests")>]
[<assembly: AssemblyProductAttribute("Brahma.FSharp")>]
[<assembly: AssemblyVersionAttribute("2.0.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2022-12-28T00:00:00.0000000+03:00")>]
[<assembly: AssemblyFileVersionAttribute("2.0.2")>]
[<assembly: AssemblyInformationalVersionAttribute("2.0.2")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","8dd2acbb7a830be3b227c0091d18ebd432aa7ce1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Brahma.FSharp.Tests"
    let [<Literal>] AssemblyProduct = "Brahma.FSharp"
    let [<Literal>] AssemblyVersion = "2.0.2"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2022-12-28T00:00:00.0000000+03:00"
    let [<Literal>] AssemblyFileVersion = "2.0.2"
    let [<Literal>] AssemblyInformationalVersion = "2.0.2"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "8dd2acbb7a830be3b227c0091d18ebd432aa7ce1"
